name: corruptify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3
  firebase_database: ^11.1.6
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  pie_chart: ^5.4.0
  timelines: ^0.1.0
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6
  file_picker: ^8.1.4
  timeline_tile: ^2.0.0
  flutter_neumorphic: ^3.2.0
  audioplayers: ^6.1.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/admin/
    - assets/images/
    - assets/ScreenUser/
    - assets/audio/splash_sound1.mp3
    
